# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Blogger
version:      0.87
version_from: lib/Net/Blogger.pm
installdirs:  site
requires:
    Carp:                          0
    CGI:                           0
    Digest::MD5:                   0
    Error:                         0
    HTTP::Cookies:                 0
    SOAP::Lite:                    0.55
    Term::ReadKey:                 0
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
